version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: your_database_name
      MYSQL_USER: your_username
      MYSQL_PASSWORD: your_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=your_database_name
      - DB_USER=your_username
      - DB_PASSWORD=your_password
    ports:
      - "8000:8000"
    volumes:
      - .:/app

volumes:
  db_data:
